name: Docker

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    env:
      PLATFORMS: linux/amd64,linux/arm64/v8

    strategy:
      fail-fast: false
      matrix:
        version:
        - ""
        - "2.2.1"
        include:
        - version: ""
          download_url: https://github.com/gpac/gpac/archive/refs/heads/master.tar.gz
        - latest: true
          version: ""

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      id: config
      run: |-
        NPROC=$(nproc)

        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_ENV
        echo "NPROC=$((NPROC*2+1))" >> $GITHUB_OUTPUT

        echo "image-owner=${{ github.repository_owner }}" >> $GITHUB_OUTPUT
        echo "image-name=${GITHUB_REPOSITORY#*/docker-}" >> $GITHUB_OUTPUT

    - name: Setup - QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ matrix.platforms || env.PLATFORMS || 'linux/amd64' }}

    - name: Setup - Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup - Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup - Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |-
          ${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
          ghcr.io/${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
        flavor: |-
          latest=${{ !!matrix.latest }}
        tags: |-
          type=raw,value=latest,enable=${{ !matrix.version }}
          type=semver,pattern={{major}}.{{minor}},value=${{ matrix.version }},enable=${{ !!matrix.version }}
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ matrix.version }},enable=${{ !!matrix.version }}

    - name: Build
      uses: docker/build-push-action@v5
      id: build
      with:
        context: .
        build-args: |
          version=${{ matrix.version }}
          ${{ matrix.download_url && format('download_url={0}', matrix.download_url) }}
        push: true
        platforms: ${{ matrix.platforms || env.PLATFORMS || 'linux/amd64' }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        annotations: ${{ steps.meta.outputs.annotations }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
