name: Docker

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    env:
      PLATFORMS: linux/amd64,linux/arm64/v8

    strategy:
      fail-fast: false
      matrix:
        version:
        - "latest"
        - "2.2.1"
        include:
        - version: "latest"
          download_url: https://github.com/gpac/gpac/archive/7a3eca90b5e2267b9d8f898415553f80eb9727b9.tar.gz
          latest: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      id: config
      uses: actions/github-script@v7
      env:
        GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
      with:
        script: |
          core.setOutput('nproc', require('os').cpus().length * 2)

          core.setOutput('image-owner', process.env.GITHUB_REPOSITORY_OWNER)
          core.setOutput('image-name', process.env.GITHUB_REPOSITORY_NAME.replace(/^docker-/, ''))

    - name: Setup - QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ matrix.platforms || env.PLATFORMS || 'linux/amd64' }}

    - name: Setup - Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup - Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup - Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Setup - Docker image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |-
          ${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
          ghcr.io/${{ steps.config.outputs.image-owner }}/${{ steps.config.outputs.image-name }}
        flavor: |-
          latest=${{ !!matrix.latest }}
        tags: |-
          type=raw,value=latest,enable=${{ matrix.version == 'latest' }}
          type=semver,pattern={{major}}.{{minor}},value=${{ matrix.version }},enable=${{ matrix.version != 'latest' }}
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ matrix.version }},enable=${{ matrix.version != 'latest' }}

    - name: Build
      uses: docker/build-push-action@v5
      id: build
      with:
        context: .
        build-args: |
          version=${{ matrix.version }}
          ${{ matrix.download_url && format('download_url={0}', matrix.download_url) }}
          MAKEFLAGS=-j${{ steps.config.outputs.NPROC }}
        push: true
        platforms: ${{ env.PLATFORMS }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ steps.meta.outputs.tags }}
        annotations: ${{ steps.meta.outputs.annotations }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
